"use client";
import Link from "next/link";import{usePathname}from"next/navigation";import{useEffect,useState}from"react";
export const map="https://maps.google.com/?q=Savoiepad+14+Eindhoven";
function Logo(){return <><img className="brandLogo" src="/gtp-logo.webp" alt="Glory Tabernacle Parish logo"/><span><strong>Glory Tabernacle</strong><small>Parish Eindhoven</small></span></>}
export function Header(){const[open,setOpen]=useState(false),pathname=usePathname();useEffect(()=>{document.documentElement.removeAttribute("data-theme");const els=document.querySelectorAll("main section, .cards article, .gallery figure");const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("inView")}),{threshold:.08,rootMargin:"0px 0px -3%"});els.forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);useEffect(()=>{setOpen(false)},[pathname]);const nav=[['/about','About'],['/events','Events'],['/gallery','Gallery'],['/contact','Contact']];return <><a className="skipLink" href="#main-content">Skip to main content</a><header className="siteHeader"><Link className="brand" href="/" aria-label="Glory Tabernacle Parish home"><Logo/></Link><button className="mobileMenu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open} aria-controls="primary-navigation">{open?"Close":"Menu"}</button><nav id="primary-navigation" className={open?"open":""} aria-label="Primary navigation">{nav.map(([href,label])=><Link key={href} href={href} className={pathname===href?"active":""} aria-current={pathname===href?"page":undefined}>{label}</Link>)}<Link className={`navCta${pathname==="/prayer-request"?" active":""}`} href="/prayer-request" aria-current={pathname==="/prayer-request"?"page":undefined}>Prayer request</Link></nav></header></>}
export function Footer(){return <footer id="contact"><div className="foot"><div><Link className="brand" href="/" aria-label="Glory Tabernacle Parish home"><Logo/></Link><p>A multicultural church family pursuing holiness, sharing hope and growing together in Christ.</p></div><Info title="Visit"><p>Wijkcentrum de Mortel<br/>Savoiepad 14<br/>5627 DX Eindhoven</p><p>Sunday · 11:00 AM</p><a href={map} target="_blank" rel="noreferrer">Open in Maps</a></Info><Info title="Explore"><Link href="/about">About us</Link><Link href="/events">Events</Link><Link href="/gallery">Gallery</Link><Link href="/anbi">ANBI</Link></Info><Info title="Connect"><a href="tel:+31634146688">+31 6 34146688</a><a href="mailto:gtpeindhoven@rccgeurope.org">Email us</a><Link href="/prayer-request">Prayer request</Link></Info></div><div className="copy">© {new Date().getFullYear()} Glory Tabernacle Parish <span>Connect · Belong · Learn · Grow</span></div></footer>}
function Info({title,children}:{title:string,children:React.ReactNode}){return <div className="info"><h3>{title}</h3>{children}</div>}
export function PageHero({kicker,title,text,visual}:{kicker:string,title:string,text:string,visual?:"about"|"events"|"gallery"|"contact"|"prayer"|"anbi"}){return <section className={`pageHero${visual?` pageHero--${visual}`:""}`}><div><p className="eyebrow pale">{kicker}</p><h1>{title}</h1><p>{text}</p></div><span className="scrollHint">Scroll to explore</span></section>}
export function Shell({children}:{children:React.ReactNode}){return <><Header/><main id="main-content">{children}</main><Footer/></>}
export function InnerCta({kicker="You are welcome",title="There is a place for you here.",text="Join us this Sunday at 11:00 AM in Eindhoven."}:{kicker?:string,title?:string,text?:string}){return <section className="innerCta"><p className="eyebrow pale">{kicker}</p><h2>{title}</h2><p>{text}</p><div className="actions"><a className="btn gold" href={map} target="_blank" rel="noreferrer">Plan your visit</a><Link className="btn outline" href="/contact">Contact us</Link></div></section>}
