import{InnerCta,PageHero,Shell,map}from"../components/SiteChrome";

const gatherings=[
 {day:"SUN",time:"11:00",title:"Sunday Celebration",place:"Wijkcentrum de Mortel · Eindhoven",text:"Sunday School, joyful worship, testimonies, prayer and the Word for every generation.",action:"Get directions",href:map},
 {day:"THU",time:"19:00",title:"Home Cell Eindhoven",place:"Eindhoven",text:"A welcoming evening of Bible study, prayer, conversation and friendship.",action:"Ask for the address",href:"/contact"},
 {day:"THU",time:"19:00",title:"Home Cell Helmond",place:"Helmond",text:"Connect with believers closer to home and grow together in faith.",action:"Ask for the address",href:"/contact"},
 {day:"THU",time:"21:00",title:"Home Cell Best",place:"Best · online option available",text:"Weekly fellowship for the Best community, with an option to join online.",action:"Request the link",href:"/contact"}
];

export default function Events(){return <Shell><PageHero visual="events" kicker="Gather with us" title="What’s happening at GTP." text="Weekly worship, home cells and special programmes for the whole family."/>
 <section className="eventIntro pad"><div><p className="eyebrow">Come as you are</p><h2>There is always room for you.</h2></div><p>Whether it is your first Sunday or you are looking for a smaller community during the week, every gathering is an opportunity to encounter God and build lasting friendships.</p></section>
 <section className="eventFeature"><div className="eventFeaturePhoto" role="img" aria-label="Glory Tabernacle Parish worship service"/><div className="eventFeatureCopy"><p className="eyebrow pale">Every Sunday</p><div className="featureTime"><strong>11:00</strong><span>AM<br/>Eindhoven</span></div><h2>Start your week in His presence.</h2><p>Expect heartfelt worship, practical teaching, prayer and a warm multicultural church family. Children are welcome and you do not need to register.</p><div className="actions"><a className="btn gold" href={map} target="_blank" rel="noreferrer">Get directions ↗</a><a className="btn outline" href="/contact">Ask a question</a></div></div></section>
 <section className="upcomingEvents pad"><div className="upcomingHead"><div><p className="eyebrow">Save the moment</p><h2>Upcoming events.</h2></div><p>Special programmes, conferences and celebrations will be announced here when new dates are confirmed.</p></div><div className="upcomingEmpty"><span className="upcomingEmptyMark">+</span><div><p className="eyebrow">Calendar update</p><h3>No upcoming events at the moment.</h3><p>There are currently no special events scheduled. You are always welcome at our weekly Sunday celebration and home-cell gatherings below.</p></div><a className="btn outlineDark" href="/contact">Ask us a question</a></div></section>
 <section className="weeklyEvents pad"><div className="weeklyHead"><div><p className="eyebrow">Our weekly rhythm</p><h2>Meet. Pray. Grow.</h2></div><p>A healthy week of faith is built through connection, prayer and the Word. Choose the gathering that works for you.</p></div><div className="rhythmPillars"><article><span>01</span><strong>Meet.</strong><p>Find your people and experience a warm, multicultural church family.</p></article><article><span>02</span><strong>Pray.</strong><p>Bring every season of life to God, together with people who care.</p></article><article><span>03</span><strong>Grow.</strong><p>Build a practical, lasting faith through Scripture and community.</p></article></div><div className="scheduleLabel"><span>Weekly schedule</span><small>Contact us for home-cell addresses or the online link</small></div><div className="eventList">{gatherings.map((item,index)=><article key={item.title}><div className="eventDate"><small>{item.day}</small><strong>{item.time}</strong></div><span className="eventNumber">0{index+1}</span><div className="eventDetails"><small>{item.place}</small><h3>{item.title}</h3><p>{item.text}</p></div><a href={item.href} target={item.href===map?"_blank":undefined} rel={item.href===map?"noreferrer":undefined}>{item.action} <b>↗</b></a></article>)}</div></section>
 <section className="specialEvents pad"><div className="specialIntro"><p className="eyebrow pale">Throughout the year</p><h2>Special moments.<br/>Shared together.</h2><p>Women’s gatherings, children’s programmes, worship nights, conferences and family celebrations are announced during the year.</p><a href="/contact">Contact us for the latest programme →</a></div><div className="specialMosaic"><div className="specialPhoto specialPhoto1" role="img" aria-label="GTP family celebration"/><div className="specialPhoto specialPhoto2" role="img" aria-label="GTP children’s programme"/></div></section>
 <InnerCta kicker="This Sunday · 11:00 AM" title="Come and worship with us."/></Shell>}
