"use client";

import{ChangeEvent,useCallback,useEffect,useMemo,useRef,useState}from"react";
type Moment={title:string;copy:string;src:string;pos:string;category:string;key?:string;uploaded?:string};
type GalleryImage={key:string;name:string;url:string;uploaded:string};
const categories=["All","Worship","Virtuous Women","Children","Youth","Choir","Baptism","Child Dedication","Community","Celebrations","Uploaded"];

export default function GalleryArchive({moments}:{moments:Moment[]}){
 const[uploads,setUploads]=useState<GalleryImage[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[category,setCategory]=useState("All"),[query,setQuery]=useState(""),[active,setActive]=useState<number|null>(null);
 const input=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{const response=await fetch("/api/gallery",{cache:"no-store"});if(response.ok){const data=await response.json();setUploads(data.images||[])}},[]);
 useEffect(()=>{load().catch(()=>setMessage("Uploaded photos could not be loaded."))},[load]);
 const all=useMemo<Moment[]>(()=>[...moments,...uploads.map(image=>({title:image.name.replace(/\.[^.]+$/,"").replace(/[-_]+/g," "),copy:"Added to the GTP gallery.",src:image.url,pos:"center",category:"Uploaded",key:image.key,uploaded:image.uploaded}))],[moments,uploads]);
 const visible=useMemo(()=>{const search=query.trim().toLowerCase();return all.filter(photo=>(category==="All"||photo.category===category)&&(!search||`${photo.title} ${photo.copy} ${photo.category}`.toLowerCase().includes(search)))},[all,category,query]);
 const close=useCallback(()=>setActive(null),[]),previous=useCallback(()=>setActive(value=>value===null?null:(value-1+visible.length)%visible.length),[visible.length]),next=useCallback(()=>setActive(value=>value===null?null:(value+1)%visible.length),[visible.length]);
 useEffect(()=>{if(active===null)return;const key=(event:KeyboardEvent)=>{if(event.key==="Escape")close();if(event.key==="ArrowLeft")previous();if(event.key==="ArrowRight")next()};document.body.classList.add("lightboxOpen");window.addEventListener("keydown",key);return()=>{document.body.classList.remove("lightboxOpen");window.removeEventListener("keydown",key)}},[active,close,next,previous]);
 useEffect(()=>setActive(null),[category,query]);
 async function upload(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files||[]);if(!files.length)return;setBusy(true);setMessage("");try{for(const file of files){const body=new FormData();body.append("photo",file);const response=await fetch("/api/gallery",{method:"POST",body});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||`Could not upload ${file.name}.`)}}await load();setMessage(`${files.length} ${files.length===1?"photo":"photos"} added to the gallery.`)}catch(error){setMessage(error instanceof Error?error.message:"The upload did not complete.")}finally{setBusy(false);if(input.current)input.current.value=""}}
 const current=active===null?null:visible[active];
 return <>
  <section className="galleryArchive pad" aria-label="Church photo gallery">
   <div className="galleryTools"><div className="filterBar" aria-label="Filter photos by category">{categories.map(item=><button key={item} type="button" className={category===item?"active":""} onClick={()=>setCategory(item)}>{item}</button>)}</div><label className="gallerySearch"><span className="srOnly">Search photos</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search photos…"/><b aria-hidden="true">⌕</b></label></div>
   <div className="galleryCount"><span>{visible.length} {visible.length===1?"photo":"photos"}</span><small>Select a photo to open</small></div>
   {visible.length?<div className="photoGrid">{visible.map((photo,index)=><button className="photoTile" key={photo.key||photo.src} type="button" onClick={()=>setActive(index)} aria-label={`Open ${photo.title}`}><img src={photo.src} alt={photo.title} loading="lazy"/><span><b>{photo.title}</b><small>{photo.category}</small></span></button>)}</div>:<div className="galleryEmpty"><h3>No photos found.</h3><p>Try another category or search term.</p></div>}
  </section>
  <section className="galleryManager pad" aria-labelledby="gallery-upload-title"><div className="uploadCopy"><p className="eyebrow">Keep the story growing</p><h2 id="gallery-upload-title">Add new moments.</h2><p>Select one or several church photos. They are safely stored and automatically join the searchable gallery above.</p><label className={`uploadButton${busy?" isBusy":""}`}><input ref={input} type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple onChange={upload} disabled={busy}/><span>{busy?"Uploading…":"Choose photos"}</span></label><p className="uploadHint">JPG, PNG, WebP or GIF · up to 12 MB per photo</p>{message&&<p className="uploadMessage" role="status">{message}</p>}</div></section>
  {current&&<div className="lightbox" role="dialog" aria-modal="true" aria-label={`${current.title}, photo ${active!+1} of ${visible.length}`} onClick={close}><button className="lightboxClose" type="button" onClick={close} aria-label="Close photo viewer">×</button><button className="lightboxNav lightboxPrev" type="button" onClick={event=>{event.stopPropagation();previous()}} aria-label="Previous photo">‹</button><div className="lightboxStage" onClick={event=>event.stopPropagation()}><img src={current.src} alt={current.title}/><div className="lightboxCaption"><div><strong>{current.title}</strong><span>{current.copy}</span></div><small>{active!+1} / {visible.length} · {current.category}</small></div></div><button className="lightboxNav lightboxNext" type="button" onClick={event=>{event.stopPropagation();next()}} aria-label="Next photo">›</button></div>}
 </>
}
