import Link from "next/link";
import {PageHero,Shell,map} from "../components/SiteChrome";

const phoneOne="+31634146688";
const phoneTwo="+31651549995";
const email="gtpeindhoven@rccgeurope.org";

export default function Contact(){return <Shell>
  <PageHero visual="contact" kicker="Let’s connect" title="We would love to hear from you." text="Whether you are planning your first visit, looking for community or simply need someone to talk to—we are here."/>
  <section className="contactWelcome pad"><div><p className="eyebrow">Come and say hello</p><h2>There is a place<br/>for you here.</h2></div><div><p className="contactLead">Church should feel like coming home. Ask us anything before you visit, or simply join us this Sunday.</p><p>Our multicultural family gathers in Eindhoven every Sunday at 11:00 AM. You do not need to register, and children are warmly welcome.</p></div></section>
  <section className="contactVisit"><div className="contactVisitPhoto" role="img" aria-label="A warm welcome at Glory Tabernacle Parish"/><div className="contactVisitPanel"><p className="eyebrow pale">Visit us this Sunday</p><div className="contactServiceTime"><strong>11:00</strong><span>AM<br/>Every Sunday</span></div><h2>Wijkcentrum<br/>de Mortel</h2><address>Savoiepad 14<br/>5627 DX Eindhoven<br/>The Netherlands</address><div className="actions"><a className="btn gold" href={map} target="_blank" rel="noreferrer">Open directions</a><Link className="btn outline" href="/events">View weekly schedule</Link></div></div></section>
  <section className="contactChannels pad"><div className="contactChannelsHead"><div><p className="eyebrow">Choose what feels easiest</p><h2>Reach out.<br/>We’ll respond.</h2></div><p>Questions about the service, home cells, children’s ministry or something else? Contact us through the channel that works best for you.</p></div><div className="contactChannelGrid"><article><span>01</span><div><small>Call us</small><h3>Speak with someone.</h3><p>For a direct conversation or a practical question about your visit.</p></div><div className="contactLinks"><a href={`tel:${phoneOne}`}>+31 6 34146688</a><a href={`tel:${phoneTwo}`}>+31 6 51549995</a></div></article><article><span>02</span><div><small>Email us</small><h3>Send us a message.</h3><p>We are happy to help with general questions, ministries and home-cell information.</p></div><a className="contactPrimaryLink" href={`mailto:${email}`}>{email}</a></article><article className="contactChannelPrayer"><span>03</span><div><small>Confidential prayer</small><h3>Let us pray with you.</h3><p>Share what is on your heart with our prayer team through the dedicated request page.</p></div><Link className="contactPrimaryLink" href="/prayer-request">Send a prayer request</Link></article></div></section>
  <section className="firstVisit pad"><div className="firstVisitIntro"><p className="eyebrow pale">Your first Sunday</p><h2>Come as<br/>you are.</h2><p>No dress code. No registration. Just a warm welcome, heartfelt worship and space to encounter God.</p></div><div className="firstVisitSteps"><article><span>01</span><div><h3>Arrive</h3><p>Doors are open before the 11:00 AM service. Our team will be ready to welcome you.</p></div></article><article><span>02</span><div><h3>Feel at home</h3><p>Choose any seat and enjoy worship, prayer, testimonies and a practical message.</p></div></article><article><span>03</span><div><h3>Stay connected</h3><p>After the service, meet the family and ask about a home cell near you.</p></div></article></div></section>
  <section className="contactFinal"><p className="eyebrow pale">Questions are always welcome</p><h2>Let’s connect.</h2><p>Call, email or meet us this Sunday in Eindhoven.</p><div className="actions"><a className="btn gold" href={`mailto:${email}`}>Email us</a><a className="btn outline" href={`tel:${phoneOne}`}>Call us</a></div></section>
</Shell>}
